# -*- coding: utf-8 -*-
"""Face Recognize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvH5v9S1APAbpvmF_4TiroQcc2787YVl
"""

!pip install face_recognition cmake dlib

#-----------------------------------
# Run Locally for better Experience
#-----------------------------------

import cgi
from base64 import b64decode
import face_recognition

formData = cgi.FieldStorage()
face_match = 0
image = formData.getvalue("current_image")
email = formData.getvalue("email")
data_url = image
header,encoded = data_url.split(",", 1)
data = b64decode(encoded)

with open("image.png", "wb") as f:
	f.write(data)

got_image = face_recognition.load_image_file("image.png")
existing_image = face_recognition.load_image_file("students/"+email+".jpg")
got_image_facialfeatures = face_recognition.face_encodings(got_image)[0]

existing_image_facialfeatures = face_recognition.face_encodings(existing_image)[0]
results = face_recognition.compare_faces([existing_image_facialfeatures],got_image_facialfeatures)

if(results[0]):
	face_match = 1
else:
	face_match = 0

print("Content-Type : text/html")
#pint()

if(face_match==1):
	print("<script>alert('welcome",email," ')</script>")
else:
	print("<script>alert('face not recognized')</script>")

# ---------------------------
# Face Matching Using Base64
# ---------------------------

import face_recognition
import base64
import os

# -------------------------------
# USER INPUT (ONLY PATHS)
# -------------------------------
email = "student1"

stored_image_path = "/content/image.png"
current_image_path = "/content/image_0 (1).jpg"

# -------------------------------
# SAFETY CHECK
# -------------------------------
if not os.path.exists(stored_image_path):
    raise FileNotFoundError("❌ Stored image not found")

if not os.path.exists(current_image_path):
    raise FileNotFoundError("❌ Current image not found")

# -------------------------------
# FUNCTION: Image → Base64
# -------------------------------
def image_to_base64(image_path):
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

# -------------------------------
# FUNCTION: Base64 → Image
# -------------------------------
def base64_to_image(base64_string, output_path):
    image_bytes = base64.b64decode(base64_string)
    with open(output_path, "wb") as f:
        f.write(image_bytes)

# -------------------------------
# CONVERT TO BASE64 (INTERNAL)
# -------------------------------
stored_base64 = image_to_base64(stored_image_path)
current_base64 = image_to_base64(current_image_path)

# -------------------------------
# OPTIONAL: SAVE BACK FROM BASE64
# (shows it really works)
# -------------------------------
stored_tmp_path = "/content/stored_tmp.png"
current_tmp_path = "/content/current_tmp.png"

base64_to_image(stored_base64, stored_tmp_path)
base64_to_image(current_base64, current_tmp_path)

# -------------------------------
# LOAD IMAGES
# -------------------------------
stored_image = face_recognition.load_image_file(stored_tmp_path)
current_image = face_recognition.load_image_file(current_tmp_path)

# -------------------------------
# FACE ENCODING
# -------------------------------
stored_faces = face_recognition.face_encodings(stored_image)
current_faces = face_recognition.face_encodings(current_image)

if not stored_faces:
    raise ValueError("❌ No face found in STORED image")

if not current_faces:
    raise ValueError("❌ No face found in CURRENT image")

# -------------------------------
# COMPARE
# -------------------------------
results = face_recognition.compare_faces(
    [stored_faces[0]],
    current_faces[0],
    tolerance=0.5
)

# -------------------------------
# RESULT
# -------------------------------
if results[0]:
    print(f"✅ Welcome {email}! Face matched.")
else:
    print("❌ Face not recognized.")

# -----------
# For Collab
# -----------

from google.colab import files

print("📌 Upload STORED (reference) image")
stored_upload = files.upload()

print("📌 Upload CURRENT (image to verify)")
current_upload = files.upload()
import face_recognition

# Get filenames
stored_image_path = list(stored_upload.keys())[0]
current_image_path = list(current_upload.keys())[0]

# Load images
stored_image = face_recognition.load_image_file(stored_image_path)
current_image = face_recognition.load_image_file(current_image_path)

# Encode faces
stored_faces = face_recognition.face_encodings(stored_image)
current_faces = face_recognition.face_encodings(current_image)

# Safety checks
if len(stored_faces) == 0:
    raise ValueError("❌ No face found in STORED image")

if len(current_faces) == 0:
    raise ValueError("❌ No face found in CURRENT image")

stored_encoding = stored_faces[0]
current_encoding = current_faces[0]

# Compare faces
results = face_recognition.compare_faces(
    [stored_encoding],
    current_encoding,
    tolerance=0.5
)

# Output
if results[0]:
    print("✅ FACE MATCHED — Welcome!")
else:
    print("❌ FACE NOT MATCHED")